export type AudiusResponse<T> = {
	data: T;
};

export type Track = {
	artwork?: {
		_1000x1000?: string;
		_150x150?: string;
		_480x480?: string;
	};
	description?: string;
	downloadable?: boolean;
	duration: number;
	favoriteCount: number;
	genre?: string;
	id: string;
	isStreamable?: string;
	mood?: string;
	permalink?: string;
	playCount: number;
	releaseDate: string;
	remixOf?: {
		tracks: { parentTrackId: string }[];
	};
	repostCount: number;
	tags?: string[];
	title: string;
	trackCid?: string;
	user: {
		albumCount: number;
		artistPickTrackId?: string;
		bio?: string;
		coverPhoto?: {
			_2000?: string;
			_640?: string;
		};
		doesFollowCurrentUser?: boolean;
		ercWallet: string;
		followeeCount: number;
		followerCount: number;
		handle: string;
		id: string;
		isAvailable: boolean;
		isDeactivated: boolean;
		isVerified: boolean;
		location?: string;
		name: string;
		playlistCount: number;
		profilePicture?: {
			_1000x1000?: string;
			_150x150?: string;
			_480x480?: string;
		};
		repostCount: number;
		splWallet: string;
		supporterCount: number;
		supportingCount: number;
		totalAudioBalance: number;
		trackCount: number;
	};
};

export type User = {
	albumCount: number;
	artistPickTrackId?: string;
	bio?: string;
	coverPhoto?: {
		_2000?: string;
		_640?: string;
	};
	doesFollowCurrentUser?: boolean;
	ercWallet: string;
	followeeCount: number;
	followerCount: number;
	handle: string;
	id: string;
	isAvailable: boolean;
	isDeactivated: boolean;
	isVerified: boolean;
	location?: string;
	name: string;
	playlistCount: number;
	profilePicture?: {
		_1000x1000?: string;
		_150x150?: string;
		_480x480?: string;
	};
	repostCount: number;
	splWallet: string;
	supporterCount: number;
	supportingCount: number;
	totalAudioBalance: number;
	trackCount: number;
};

export type Playlist = {
	artwork?: {
		'1000x1000'?: string;
		'150x150'?: string;
		'480x480'?: string;
	};
	coverArtSizes?: string;
	description?: string;
	favoriteCount: number;
	id: string;
	isAlbum: boolean;
	isImageAutogenerated?: boolean;
	isPrivate: boolean;
	permalink?: string;
	playlistContents: {
		metadataTimestamp: number;
		timestamp: number;
		trackId: string;
	};
	playlistName: string;
	repostCount: number;
	totalPlayCount: number;
	user: {
		albumCount: number;
		artistPickTrackId?: string;
		bio?: string;
		coverPhoto?: {
			_2000?: string;
			_640?: string;
		};
		doesFollowCurrentUser?: boolean;
		ercWallet: string;
		followeeCount: number;
		followerCount: number;
		handle: string;
		id: string;
		isAvailable: boolean;
		isDeactivated: boolean;
		isVerified: boolean;
		location?: string;
		name: string;
		playlistCount: number;
		profilePicture?: {
			_1000x1000?: string;
			_150x150?: string;
			_480x480?: string;
		};
		repostCount: number;
		splWallet: string;
		supporterCount: number;
		supportingCount: number;
		totalAudioBalance: number;
		trackCount: number;
	};
};

export type Album = {
	artwork?: {
		_1000x1000?: string;
		_150x150?: string;
		_480x480?: string;
	};
	coverArtSizes?: string;
	description?: string;
	favoriteCount: number;
	id: string;
	isImageAutogenerated?: boolean;
	isPrivate: boolean;
	permalink?: string;
	playlistContents: {
		metadataTimestamp: number;
		timestamp: number;
		trackId: string;
	};
	playlistName: string;
	repostCount: number;
	totalPlayCount: number;
	user: {
		albumCount: number;
		artistPickTrackId?: string;
		bio?: string;
		coverPhoto?: {
			_2000?: string;
			_640?: string;
		};
		doesFollowCurrentUser?: boolean;
		ercWallet: string;
		followeeCount: number;
		followerCount: number;
		handle: string;
		id: string;
		isAvailable: boolean;
		isDeactivated: boolean;
		isVerified: boolean;
		location?: string;
		name: string;
		playlistCount: number;
		profilePicture?: {
			_1000x1000?: string;
			_150x150?: string;
			_480x480?: string;
		};
		repostCount: number;
		splWallet: string;
		supporterCount: number;
		supportingCount: number;
		totalAudioBalance: number;
		trackCount: number;
	};
};
