# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
viaIR = true
auto_detect_solc = false
bytecode_hash = "none"
evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
fuzz = { runs = 1_000 }
gas_reports = ["*"]
out = "out"
script = "script"
solc = "0.8.23"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
sepolia = "${ETH_SEPOLIA}"
